### ISSUE TITLE
influxdb sink error

### ISSUE THREAD

**Issue by bscott** [armon/statsite#166] opened 2015-12-20 13:59 UTC
Getting this every 5secs from Statsite log:

```
Traceback (most recent call last):
  File "/opt/statsite/sinks/influxdb.py", line 247, in <module>
    main(sys.stdin.read(), *sys.argv[1:])
  File "/opt/statsite/sinks/influxdb.py", line 242, in main
    influxdb.flush09(metrics.splitlines())
  File "/opt/statsite/sinks/influxdb.py", line 143, in flush09
    for k, v, ts in metrics:
ValueError: too many values to unpack
statsite[2434]: Streaming command exited with status 1
```

**Comment by kuba--** [comment] 2015-12-22 00:02
I can't reproduce this issue - what your statsite flushes to the sink or what are you sending to statsite?
What version of InfluxDB do you use?

Btw. I sent a pull request https://github.com/armon/statsite/pull/167 but I do not think it's related.

**Comment by kuba--** [comment] 2016-01-27 18:21
@bscott Can we close this issue?

**Comment by armon** [comment] 2016-01-30 02:53
@kuba-- Yep!
@bscott Please re-open if there is still an issue!

**Closed by armon** 2016-01-30 02:53 UTC
