### ISSUE TITLE
Duplicate output?

### ISSUE THREAD

**Issue by CpuID** [armon/statsite#187] opened 2016-03-23 03:56 UTC
Seems like in the past couple of days (maybe the autotools cutover), something changed has caused duplicate output to occur for every line. See below an example of a built binary startup (no configuration, ignore the red herring):

```
statsite[1]: Starting statsite.
statsite[1]: Starting statsite.
statsite[1]: stdin is disabled
statsite[1]: stdin is disabled
statsite[1]: Listening on tcp ':::8125'
statsite[1]: Listening on tcp ':::8125'
statsite[1]: Listening on udp ':::8125'.
statsite[1]: Listening on udp ':::8125'.
streaming: applet not found
statsite[1]: Streaming command exited with status 127
statsite[1]: Streaming command exited with status 127
streaming: applet not found
statsite[1]: Streaming command exited with status 127
statsite[1]: Streaming command exited with status 127
streaming: applet not found
statsite[1]: Streaming command exited with status 127
statsite[1]: Streaming command exited with status 127
streaming: applet not found
statsite[1]: Streaming command exited with status 127
statsite[1]: Streaming command exited with status 127
^Cstatsite[1]: Received signal [Interrupt]! Exiting...
statsite[1]: Received signal [Interrupt]! Exiting...
statsite[1]: Closed connection. [6]
statsite[1]: Closed connection. [6]
streaming: applet not found
statsite[1]: Streaming command exited with status 127
statsite[1]: Streaming command exited with status 127
```

Built and tested under Alpine Linux 3.3 on master - git ref `a6a3c67530bc88bdc6555cdf14dde2ebef39e4c9`

Dockerfile used: https://gist.github.com/CpuID/0d75bc5370c65681f659

**Comment by armon** [comment] 2016-04-09 01:30
I wonder if you are just getting the double output of stderr + syslog. The autotools change should not have affected this, but all the logging goes through syslog.

**Comment by CpuID** [comment] 2016-04-09 03:43
Interesting, just started up the container image using `docker run -it imageid sh`, and ran `./src/statsite -f ./statsite.conf > /usr/src/statsite/stdout 2> /usr/src/statsite/stderr` from a shell to identify which FD's are getting what. See below:

```
/usr/src/statsite # ./src/statsite -f ./statsite.conf > /usr/src/statsite/stdout 2> /usr/src/statsite/stderr
statsite[22]: Starting statsite.
statsite[22]: stdin is disabled
statsite[22]: Listening on tcp ':::8125'
statsite[22]: Listening on udp ':::8125'.
statsite[22]: Streaming command exited with status 127
statsite[22]: Streaming command exited with status 127
statsite[22]: Streaming command exited with status 127
^Cstatsite[22]: Received signal [Interrupt]! Exiting...
statsite[22]: Streaming command exited with status 127
/usr/src/statsite # ls -la std*
-rw-r--r--    1 root     root           534 Apr  9 03:24 stderr
-rw-r--r--    1 root     root             0 Apr  9 03:23 stdout
/usr/src/statsite # cat stderr
statsite[22]: Starting statsite.
statsite[22]: stdin is disabled
statsite[22]: Listening on tcp ':::8125'
statsite[22]: Listening on udp ':::8125'.
streaming: applet not found
statsite[22]: Streaming command exited with status 127
streaming: applet not found
statsite[22]: Streaming command exited with status 127
streaming: applet not found
statsite[22]: Streaming command exited with status 127
statsite[22]: Received signal [Interrupt]! Exiting...
streaming: applet not found
statsite[22]: Streaming command exited with status 127
```

So stdout gets nothing, stderr gets one set of output, and some other FD is getting a copy also... you mentioned syslog? There is no syslog daemon running in the container, here is an lsof output for the running process:

```
# lsof -n | grep -i 22
22	/usr/src/statsite/src/statsite	/12
22	/usr/src/statsite/src/statsite	/usr/src/statsite/stdout
22	/usr/src/statsite/src/statsite	/usr/src/statsite/stderr
22	/usr/src/statsite/src/statsite	socket:[233468]
22	/usr/src/statsite/src/statsite	anon_inode:[eventpoll]
22	/usr/src/statsite/src/statsite	socket:[233469]
22	/usr/src/statsite/src/statsite	socket:[233470]
```

Any recommended thoughts on the best way to deduplicate this? Is it worth just dropping one of the FD outputs to /dev/null? Which one is best to retain output wise?

**Comment by armon** [comment] 2016-04-13 02:22
@CpuID I would try running the docker container without a TTY attached `-i`. That might be causing the issue.

**Comment by lsiudut** [comment] 2016-05-11 12:02
Actually I ran into same issue.

The problem is, that statsite is execve-ing stream command as follows:

`execve("/bin/sh", ["streaming", "-c", "/statsite/sink.sh"]`

Alpine is using ash as default interpreter. It's considering first environment variable as applet name (busybox does similar thing). As streaming is not registered applet it's throwing the error.

Hacky but working solution is to install bash and include below in Dockerfile:

`RUN ln -sf /bin/bash /bin/sh`

**Comment by armon** [comment] 2016-05-21 00:26
Closing, please re-open if you have more info.

**Closed by armon** 2016-05-21 00:26 UTC

**Comment by hectcastro** [comment] 2016-07-12 01:51
I think this issue has more to do with Alpine Linux than Statsite. I was able to get things working by installing `bash` and symlinking `/bin/bash` over `/bin/sh`.

**Comment by anlutro** [comment] 2018-08-24 14:36
From what I can tell, this is happening because we set `LOG_CONS` which will send messages to stderr if they fail to be sent to a syslog daemon, but we also set `LOG_PERROR` which prints everything to stderr. These flags don't cancel eachother out.

https://github.com/statsite/statsite/blob/664df5a497dce7fa198982708da90531cbae1a32/src/statsite.c#L110-L112

What about changing these lines of code to something like this, which I think is more correct:

```c
    if (daemonize) {
        flags |= LOG_CONS;
    } else {
        flags |= LOG_PERROR;
    }
```

**Comment by szaydel** [comment] 2018-08-24 15:01
It might be more useful to expose a flag that gives some additional control over behaviour.
